version: '3.8'

services:
  # Main application service
  app:
    build:
      context: .
      dockerfile: deploy/docker/Dockerfile.dev
    container_name: lumi-go-app
    ports:
      - "8080:8080"  # HTTP API
      - "8081:8081"  # gRPC/Connect RPC
      - "9090:9090"  # Prometheus metrics
      - "2345:2345"  # Delve debugger (dev only)
    volumes:
      - .:/app
      - go-modules:/go/pkg/mod
    environment:
      # Service configuration
      - LUMI_SERVICE_ENVIRONMENT=development
      - LUMI_SERVICE_LOGLEVEL=debug

      # Optional: Enable external services by providing URLs
      # - LUMI_CLIENTS_DATABASE_ENABLED=true
      # - LUMI_CLIENTS_DATABASE_URL=postgres://user:pass@host:5432/db?sslmode=disable
      # - LUMI_CLIENTS_REDIS_ENABLED=true
      # - LUMI_CLIENTS_REDIS_URL=redis://host:6379/0
      # - LUMI_CLIENTS_TRACING_ENABLED=true
      # - LUMI_CLIENTS_TRACING_ENDPOINT=localhost:4317
    networks:
      - lumi-network
    restart: unless-stopped

  # NOTE: For external services (postgres, redis, grafana, etc.),
  # use the dedicated templates:
  # - templates/lumi-postgres
  # - templates/lumi-redis
  # - templates/lumi-grafana
  # Or use cloud-managed services

networks:
  lumi-network:
    driver: bridge

volumes:
  go-modules:
